# -*- coding: utf-8 -*-
"""
印刷機選定マスタ（初期値）

2026-09-29 にシール堂印刷 新保様よりChatWorkでご提供いただいた「印刷機選定.xlsx」を取り込んだもの。
各印刷機の対応可否（色数・加工・サイズ）から、仕様に合う機種の候補を絞り込むために使う。
"""

DEFAULT_MACHINES = [
    {
        "name": "コニカ（印刷のみ）", "category": "オンデマンド",
        "desc": "ロールTOロールのため印刷後後加工機処理必要",
        "color_note": "特色指定は苦手色あり（特に金赤・オレンジ・明るい紫・明るい緑）",
        "cond1": "ホイル紙・塩ビ・サテン印刷NG", "cond2": "オフセット印刷と同等品質を想定",
        "color_mode": "フルカラー", "max_colors": 4, "ng_color": "金・銀・白・透明ニス",
        "plate_needed": False, "half_cut": False, "full_cut": False, "cut": False, "emboss": False,
        "max_h": 230, "max_w": 300, "seamless": False, "back_print": True, "back_print_note": "厚口B不可",
        "variable": False,
        "menzuke_note": "紙巾250㎜（印刷有効巾240㎜に面付だが後加工機と製品仕様に合わせる）",
    },
    {
        "name": "PJ（印刷のみ）", "category": "オンデマンド",
        "desc": "ロールTOロールのため印刷後後加工機処理必要",
        "color_note": "特色指定は苦手色あり（特に金赤・オレンジ・明るい紫・明るい緑）",
        "cond1": "サテン印刷NG", "cond2": "マスキングテープシームレス印刷時・シリアル可変時選択",
        "color_mode": "フルカラー", "max_colors": 4, "ng_color": "特色・金・銀・白・透明ニス",
        "plate_needed": False, "half_cut": False, "full_cut": False, "cut": False, "emboss": False,
        "max_h": 200, "max_w": 300, "seamless": True, "back_print": True, "back_print_note": "厚口B不可",
        "variable": True,
        "menzuke_note": "※5,000枚以上/2面付　※6,000枚以上/3面付　※8,000枚以上/4面付　※10,000枚以上/5面付",
    },
    {
        "name": "間欠JNAS250", "category": "トツ版印刷機",
        "desc": "印刷+ラミネート+ハーフカット（ハーフラミネート・全抜き不可）",
        "color_note": "特色可",
        "cond1": "アート・ミラー・ホイル紙・フィルム材料の印刷適正良好", "cond2": "特にベタ印刷・アミ印刷あり時に選択",
        "color_mode": "特色可", "max_colors": 5, "ng_color": None,
        "plate_needed": True, "half_cut": True, "full_cut": False, "cut": True, "emboss": False,
        "max_h": 230, "max_w": 200, "seamless": False, "back_print": True, "back_print_note": "",
        "variable": False,
        "menzuke_note": "※5,000枚以上/2面付　※6,000枚以上/3面付　※8,000枚以上/4面付　※10,000枚以上/5面付",
    },
    {
        "name": "間欠ES150", "category": "トツ版印刷機",
        "desc": "印刷+ラミネート+ハーフカット（ハーフラミネート・全抜き不可）",
        "color_note": "特色可",
        "cond1": "アート・ミラー・ホイル紙・フィルム材料の印刷適正良好", "cond2": "特にベタ印刷・アミ印刷あり時に選択",
        "color_mode": "特色可", "max_colors": 4, "ng_color": None,
        "plate_needed": True, "half_cut": True, "full_cut": False, "cut": True, "emboss": False,
        "max_h": 130, "max_w": 80, "seamless": False, "back_print": False, "back_print_note": "",
        "variable": False,
        "menzuke_note": "※5,000枚以上/2面付　※6,000枚以上/3面付　※8,000枚以上/4面付　※10,000枚以上/5面付",
    },
    {
        "name": "平圧270", "category": "トツ版印刷機",
        "desc": "印刷+ラミネート+ハーフカット",
        "color_note": "特色可",
        "cond1": "上質や和紙系での印刷適正良好", "cond2": "主にトツ文字印刷時に選択",
        "color_mode": "特色可", "max_colors": 3, "ng_color": None,
        "plate_needed": True, "half_cut": True, "full_cut": True, "cut": True, "emboss": True,
        "max_h": 200, "max_w": 110, "seamless": False, "back_print": False, "back_print_note": "",
        "variable": False,
        "menzuke_note": "※5,000枚以上/2面付　※6,000枚以上/3面付　※8,000枚以上/4面付　※10,000枚以上/5面付",
    },
    {
        "name": "平圧150", "category": "トツ版印刷機",
        "desc": "印刷+ラミネート+ハーフカット",
        "color_note": "特色可",
        "cond1": "上質や和紙系での印刷適正良好", "cond2": "主にトツ文字印刷時に選択",
        "color_mode": "特色可", "max_colors": 2, "ng_color": None,
        "plate_needed": True, "half_cut": True, "full_cut": True, "cut": True, "emboss": True,
        "max_h": 130, "max_w": 80, "seamless": False, "back_print": False, "back_print_note": "",
        "variable": False,
        "menzuke_note": "※5,000枚以上/2面付　※6,000枚以上/3面付　※8,000枚以上/4面付　※10,000枚以上/5面付",
    },
    {
        "name": "箔押し加工機 HD330", "category": "箔押し加工機",
        "desc": "印刷+ラミネート+ハーフカット",
        "color_note": "特色可",
        "cond1": "箔押し案件　もしくは後加工機として使用", "cond2": None,
        "color_mode": "箔押しのみ", "max_colors": None, "ng_color": "箔押しのみ",
        "plate_needed": True, "half_cut": True, "full_cut": True, "cut": True, "emboss": True,
        "max_h": 300, "max_w": 300, "seamless": False, "back_print": False, "back_print_note": "",
        "variable": False,
        "menzuke_note": "※5,000枚以上/2面付　※6,000枚以上/3面付　※8,000枚以上/4面付　※10,000枚以上/5面付",
    },
    {
        "name": "箔押し加工機 HD270", "category": "箔押し加工機",
        "desc": "印刷+ラミネート+ハーフカット",
        "color_note": "特色可",
        "cond1": "箔押し案件　もしくは後加工機として使用", "cond2": None,
        "color_mode": "箔押しのみ", "max_colors": None, "ng_color": "箔押しのみ",
        "plate_needed": True, "half_cut": True, "full_cut": True, "cut": False, "emboss": True,
        "max_h": 250, "max_w": 170, "seamless": False, "back_print": False, "back_print_note": "",
        "variable": False,
        "menzuke_note": "※5,000枚以上/2面付　※6,000枚以上/3面付　※8,000枚以上/4面付　※10,000枚以上/5面付",
    },
    {
        "name": "ロータリーP25", "category": "トツ版印刷機",
        "desc": "印刷+ラミネート+ハーフカット（ハーフラミネート・全抜き不可）",
        "color_note": "特色可",
        "cond1": "アート・ミラー・ホイル紙・フィルム材料への印刷適性良い", "cond2": "使用材料3000ｍ以上の場合を想定",
        "color_mode": "特色可", "max_colors": 3, "ng_color": None,
        "plate_needed": True, "half_cut": True, "full_cut": False, "cut": False, "emboss": False,
        "max_h": 170, "max_w": 170, "seamless": False, "back_print": False, "back_print_note": "",
        "variable": False,
        "menzuke_note": "ロータリーは面付をした上で3000ｍ以上印刷する場合に選択",
    },
]
